### PR TITLE
port to 1.20.6

### LINKED ISSUE #3: crashes server on 1.20.6 after jumping
[crash-2024-05-29_17.30.47-server.txt](https://github.com/ix0rai/ramel/files/15486706/crash-2024-05-29_17.30.47-server.txt)
[latest.log](https://github.com/ix0rai/ramel/files/15486707/latest.log)

### PR DESCRIPTION
**Pull request by orifu**
port to 1.20.6. i also added fapi as a runtime dep which stops modmenu screaming

### CODE REVIEW

**Review by eristhea — APPROVED** [review]

**Comment by eristhea** [comment]
what happened to the missing field error?

**Comment by orifu** [comment]
> what happened to the missing field error?

`getBoundingBox` was changed to take a pose (i used `.getPose()`) but i think the returned box was centred around the origin? i can look into it more

**Comment by orifu** [comment]
i replaced `getBoundingBox` with `getBounds` which (i think) is used for suffocation, pushing, and probably some other stuff

**Comment by orifu** [comment]
actually they might just be the same method? idk im running in circles https://github.com/QuiltMC/quilt-mappings/commit/f8a43941e25d36e8193e06503bb20dc9126460de#diff-2317f530cef9407ee047c4c5c146d927e9c8aab223817d27de500736542dac38

**Comment by orifu** [comment]
yeah the old method `m_idziptjx` was removed in 24w03a (https://github.com/QuiltMC/quilt-mappings/commit/c8cfac4fab4b362b5e3a468f0c8c620213e4fd0b#diff-2317f530cef9407ee047c4c5c146d927e9c8aab223817d27de500736542dac38) and was replaced with `m_lgqlkcep` (theyre both `getBoundingBox()Lnet/minecraft/world/phys/AABB;`) and then mapped in the above commit you did. so. theyre the same method. basically

**Pull request merged**
